[Distribution]
Distribution=arch

[Output]
Format=directory

[Content]
Packages=
    base
    nano
    libcap
    shadow
    sudo

Environment=SYSTEMD_FIRSTBOOT_USER=sysadmin
Password=sysadmin:1234

RootPassword=